Improving gpu switching

diff --git a/microk8s-resources/wrappers/run-containerd-with-args b/microk8s-resources/wrappers/run-containerd-with-args
--- a/microk8s-resources/wrappers/run-containerd-with-args
+++ b/microk8s-resources/wrappers/run-containerd-with-args
@@ -8,8 +8,10 @@ if [ -d "/etc/apparmor.d" ]; then
   echo "Using a default profile template"
   cp ${SNAP}/containerd-profile /etc/apparmor.d/cri-containerd.apparmor.d
   echo "Reloading AppArmor profiles"
-  service apparmor reload
-  echo "AppArmor patched"
+  if ! service apparmor reload
+  then
+    echo "AppArmor profiles loading failed. AppArmor may be unavailable on this host."
+  fi
 fi
 
 app=containerd
